export * from './login.js';
export * from './register.js';
export * from './logout.js';
export * from './updatePatient.js';
export * from './deletePatient.js';
export * from './getAllPatients.js';
export * from './getPatientById.js';
export * from './resetPassword.js';
export * from './forgottenPassword.js';